In [2]:
import pandas as pd
import numpy as np
import os
 
from sklearn.model_selection import train_test_split, learning_curve, RandomizedSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import label_binarize
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_recall_fscore_support,
    roc_curve,
    auc,
    precision_recall_curve,
)
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
 
sns.set_theme(style="whitegrid")

In [3]:
# Load Dataset
df = pd.read_csv("../data/engineered/deforestation_training.csv")

# Features and Target
X = df.drop("Deforestation_Risk", axis=1)
y = df["Deforestation_Risk"]

In [4]:
# Data Splitting(70% Train, 15% Validation 15% Testing)
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Training:", X_train.shape)
print("Validation:", X_val.shape)
print("Testing:", X_test.shape)

Training: (975, 25)
Validation: (209, 25)
Testing: (209, 25)


In [5]:
# Hyperparameter Tuning with Cross-Validation
# (search happens ONLY on training data; val/test remain untouched)
param_dist = {
    "n_estimators": [100, 200, 300, 400, 500],
    "max_depth": [5, 10, 15, 20, 30, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"],
    "class_weight": ["balanced", "balanced_subsample", None],
}
 
base_model = RandomForestClassifier(random_state=42, n_jobs=-1)
 
cv_strategy = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
 
search = RandomizedSearchCV(
    estimator=base_model,
    param_distributions=param_dist,
    n_iter=40,
    scoring="f1_macro",
    cv=cv_strategy,
    random_state=42,
    n_jobs=-1,
    verbose=1,
    refit=True,
)
 
print("\nRunning cross-validated hyperparameter search...")
search.fit(X_train, y_train)
 
print("\nBest Parameters Found:")
print(search.best_params_)
print(f"Best Cross-Validation Macro F1: {search.best_score_:.4f}")
 
model = search.best_estimator_


Running cross-validated hyperparameter search...
Fitting 5 folds for each of 40 candidates, totalling 200 fits

Best Parameters Found:
{'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20, 'class_weight': 'balanced_subsample'}
Best Cross-Validation Macro F1: 0.9958


In [6]:
# Validation
val_pred = model.predict(X_val)

print("\nValidation Accuracy:", accuracy_score(y_val, val_pred))
print("Validation Macro F1 :", f1_score(y_val, val_pred, average="macro"))

# Test Evaluation
test_pred = model.predict(X_test)
test_proba = model.predict_proba(X_test)
 
accuracy = accuracy_score(y_test, test_pred)
precision = precision_score(y_test, test_pred, average="weighted")
recall = recall_score(y_test, test_pred, average="weighted")
f1 = f1_score(y_test, test_pred, average="weighted")
macro_f1 = f1_score(y_test, test_pred, average="macro")
 
print("\nFinal Test Results")
print("---------------------")
print("Accuracy        :", accuracy)
print("Precision       :", precision)
print("Recall          :", recall)
print("F1 Score (wtd)  :", f1)
print("F1 Score (macro):", macro_f1)
 
print("\nClassification Report")
print(classification_report(y_test, test_pred))
 
print("\nConfusion Matrix")
print(confusion_matrix(y_test, test_pred))

# Feature Importance
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})
 
importance = importance.sort_values(
    by="Importance",
    ascending=False
)
 
print("\nTop 10 Important Features")
print(importance.head(10))
 
# Save Feature Importance
importance.to_csv(
    "../src/feature_importance.csv",
    index=False
)


Validation Accuracy: 1.0
Validation Macro F1 : 1.0

Final Test Results
---------------------
Accuracy        : 0.9952153110047847
Precision       : 0.9952641343618787
Recall          : 0.9952153110047847
F1 Score (wtd)  : 0.9952071320492374
F1 Score (macro): 0.9954415954415955

Classification Report
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        97
           1       1.00      1.00      1.00        53
           2       1.00      0.98      0.99        59

    accuracy                           1.00       209
   macro avg       1.00      0.99      1.00       209
weighted avg       1.00      1.00      1.00       209


Confusion Matrix
[[97  0  0]
 [ 0 53  0]
 [ 1  0 58]]

Top 10 Important Features
                       Feature  Importance
1           Tree_Cover_Loss_ha    0.432970
4               Fire_Incidents    0.124740
5         Illegal_Logging_Flag    0.117572
0               Forest_Area_ha    0.115630
2           Annual_R

In [7]:
# VISUALIZATIONS 

CLASS_NAMES = ["Low", "Medium", "High"] 
PLOTS_DIR = "../visuals/model_outputs"
os.makedirs(PLOTS_DIR, exist_ok=True)

print("\nGenerating visualizations...")
 
# 1. Confusion Matrix — raw and normalized
cm = confusion_matrix(y_test, test_pred)
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
 
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES, ax=axes[0])
axes[0].set_title("Confusion Matrix (Counts)")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")
 
sns.heatmap(cm_norm, annot=True, fmt=".2%", cmap="Blues",
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES, ax=axes[1])
axes[1].set_title("Confusion Matrix (Row-Normalized %)")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")
plt.tight_layout()
plt.savefig(f"{PLOTS_DIR}/confusion_matrix.png", dpi=150)
plt.close()
print("Saved: confusion_matrix.png")
 
# 2. Feature Importance (top 15)
plt.figure(figsize=(8, 6))
sns.barplot(data=importance.head(15), x="Importance", y="Feature", palette="viridis")
plt.title("Top 15 Feature Importances — Random Forest")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.tight_layout()
plt.savefig(f"{PLOTS_DIR}/feature_importance.png", dpi=150)
plt.close()
print("Saved: feature_importance.png")
 
# 3. Per-Class Precision / Recall / F1
prec_c, rec_c, f1_c, support_c = precision_recall_fscore_support(y_test, test_pred)
metrics_df = pd.DataFrame({
    "Class": CLASS_NAMES,
    "Precision": prec_c,
    "Recall": rec_c,
    "F1-score": f1_c,
}).melt(id_vars="Class", var_name="Metric", value_name="Score")
 
plt.figure(figsize=(8, 5))
sns.barplot(data=metrics_df, x="Class", y="Score", hue="Metric")
plt.ylim(0.9, 1.02)  # zoomed in since scores are high — widen if your scores are lower
plt.title("Precision, Recall, F1-score by Class")
plt.tight_layout()
plt.savefig(f"{PLOTS_DIR}/per_class_metrics.png", dpi=150)
plt.close()
print("Saved: per_class_metrics.png")
 
# 4. ROC Curves (One-vs-Rest, multi-class)
classes_sorted = sorted(y.unique())
y_test_bin = label_binarize(y_test, classes=classes_sorted)
 
plt.figure(figsize=(7, 6))
for i, cls in enumerate(classes_sorted):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], test_proba[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{CLASS_NAMES[i]} (AUC = {roc_auc:.3f})")
plt.plot([0, 1], [0, 1], "k--", alpha=0.4, label="Random chance")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves — One-vs-Rest by Risk Class")
plt.legend(loc="lower right")
plt.tight_layout()
plt.savefig(f"{PLOTS_DIR}/roc_curves.png", dpi=150)
plt.close()
print("Saved: roc_curves.png")
 
# 5. Precision-Recall Curves
plt.figure(figsize=(7, 6))
for i, cls in enumerate(classes_sorted):
    prec_curve, rec_curve, _ = precision_recall_curve(y_test_bin[:, i], test_proba[:, i])
    plt.plot(rec_curve, prec_curve, label=f"{CLASS_NAMES[i]}")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curves by Risk Class")
plt.legend(loc="lower left")
plt.tight_layout()
plt.savefig(f"{PLOTS_DIR}/precision_recall_curves.png", dpi=150)
plt.close()
print("Saved: precision_recall_curves.png")
 
# 6. Cross-Validation Hyperparameter Search Results
cv_results = pd.DataFrame(search.cv_results_).sort_values(
    "mean_test_score", ascending=False
)
cv_results["n_estimators"] = cv_results["params"].apply(lambda d: d["n_estimators"])
cv_results["max_depth"] = cv_results["params"].apply(lambda d: d["max_depth"])
 
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
sns.boxplot(data=cv_results, x="n_estimators", y="mean_test_score", ax=axes[0])
axes[0].set_title("CV Macro F1 by n_estimators")
axes[0].set_ylabel("Mean CV Macro F1")
 
sns.boxplot(data=cv_results, x="max_depth", y="mean_test_score", ax=axes[1])
axes[1].set_title("CV Macro F1 by max_depth")
axes[1].set_ylabel("Mean CV Macro F1")
plt.tight_layout()
plt.savefig(f"{PLOTS_DIR}/cv_search_results.png", dpi=150)
plt.close()
print("Saved: cv_search_results.png")
 
# 7. Predicted vs Actual Class Distribution
actual_counts = pd.Series(y_test).value_counts().sort_index()
pred_counts = pd.Series(test_pred).value_counts().sort_index()
dist_df = pd.DataFrame({"Actual": actual_counts, "Predicted": pred_counts}).fillna(0)
dist_df.index = CLASS_NAMES
 
dist_df.plot(kind="bar", figsize=(7, 5))
plt.title("Actual vs Predicted Class Distribution (Test Set)")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(f"{PLOTS_DIR}/class_distribution.png", dpi=150)
plt.close()
print("Saved: class_distribution.png")
 
# 8. Learning Curve (train vs validation score as training size grows)
train_sizes, train_scores, val_scores = learning_curve(
    model,
    X_train,
    y_train,
    cv=cv_strategy,
    scoring="f1_macro",
    train_sizes=np.linspace(0.1, 1.0, 8),
    n_jobs=-1,
    random_state=42,
)
train_mean = train_scores.mean(axis=1)
val_mean = val_scores.mean(axis=1)
 
plt.figure(figsize=(7, 5))
plt.plot(train_sizes, train_mean, "o-", label="Training score")
plt.plot(train_sizes, val_mean, "o-", label="Cross-validation score")
plt.xlabel("Training Set Size")
plt.ylabel("Macro F1 Score")
plt.title("Learning Curve — Random Forest")
plt.legend(loc="best")
plt.tight_layout()
plt.savefig(f"{PLOTS_DIR}/learning_curve.png", dpi=150)
plt.close()
print("Saved: learning_curve.png")
 
print(f"\nAll plots saved to: {PLOTS_DIR}/")


Generating visualizations...
Saved: confusion_matrix.png


C:\Users\HP PAVILION\AppData\Local\Temp\ipykernel_19732\2601637967.py:32: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=importance.head(15), x="Importance", y="Feature", palette="viridis")


Saved: feature_importance.png
Saved: per_class_metrics.png
Saved: roc_curves.png
Saved: precision_recall_curves.png
Saved: cv_search_results.png
Saved: class_distribution.png
Saved: learning_curve.png

All plots saved to: ../visuals/model_outputs/


In [8]:
# Save Metrics
with open("../src/metrics.txt", "w") as f:
    f.write("Best Hyperparameters:\n")
    f.write(f"{search.best_params_}\n\n")
    f.write(f"Best CV Macro F1: {search.best_score_:.4f}\n\n")
    f.write(f"Validation Accuracy: {accuracy_score(y_val, val_pred)}\n")
    f.write(f"Validation Macro F1: {f1_score(y_val, val_pred, average='macro')}\n\n")
    f.write(f"Accuracy : {accuracy}\n")
    f.write(f"Precision: {precision}\n")
    f.write(f"Recall   : {recall}\n")
    f.write(f"F1 Score (weighted): {f1}\n")
    f.write(f"F1 Score (macro)   : {macro_f1}\n\n")
    f.write(classification_report(y_test, test_pred))

# Save Cross-Validation Search Results
cv_results = pd.DataFrame(search.cv_results_).sort_values(
    "mean_test_score", ascending=False
)
cv_results.to_csv("../src/cv_search_results.csv", index=False)

# Save Model
joblib.dump(model, "../src/random_forest_model.pkl")

print("\nModel Saved Successfully!")


Model Saved Successfully!
